<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageId>WorkflowCore.DesktopLite</PackageId>
    <Title>WorkflowCore Desktop Lite</Title>
    <Version>2.0.0</Version>
    <PackageOutputPath>..\..\doc\nuget</PackageOutputPath>
    <PackageIcon>workflow.png</PackageIcon>
    <Description>为流程的构建提供便捷条件</Description>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Authors>Lejoy</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/lejoycoder/WorkflowCore</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lejoycoder/WorkflowCore</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>workflow;orchestration;engine;dotnet</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\..\doc\nuget\workflow.png" Pack="True" PackagePath="\" />
  </ItemGroup>

</Project>
